languageCode = "en-us"
title = "Habit vs Fear"
description = "Take control. Be better. Play to win."
baseURL = "http://localhost:1313/"
theme = "hugo-theme-massively"
googleanalytics = ""
disqusShortname = ""
disableKinds = ["taxonomy", "taxonomyTerm", "section"]

# [params]
  # set below parameter to define a favicon
  # favicon = "favicon.ico"
  # set to change date format
  # dateFormat = "2.1.2006"

# Below parameters can be set to override default post settings
# [params.posts]
#     folderName = "post"
#     pageSize = "6"
#     featuredPost = true
#     paginationPages = 2
#     showFirstLast = false